### PR TITLE
Check batch size

### LINKED ISSUE #13: Add control flow for download size
## Checklist

- Select Project Label
- Select Sub-Project Milestone

## Feature Description

Since the downloaded set might be large, we want to allow the user to cancel a downloading job that might be too big before it happens. 

## Developer Notes

```
def check_download_size_with_user(size):
    user_agreement = False
    while not user_agreement:
         # ask user if size is alright
    return True
```

## Known Blockers

- None

## Sub-Tasks

- None

## Acceptance Criteria

- [x] If #10 is done, add this check
- [x] Tested

### PR DESCRIPTION
**Pull request by camenpihor**
fixes #13 

## Changes

- adds bin script for downloading data
- in bin script ask user if they are sure about download if download exceeds 10gb
- updates parameters and tests accordingly
- tests bin script
- notebook for showing downloading functionality

### CODE REVIEW

**Comment by camenpihor** [comment]
Good call on adding some validation for `persist_directory`. 

At freebird we have never tested click, I did add a test at `tests/it/test_bin_scripts.py` which should be sufficient, though!

**Comment by camenpihor** [comment]
@Ferrumofomega Added some more tests for the bin script and I added validation for the `persist_directory` arg

**Comment by camenpihor** [comment]
Can test all this out by pulling this branch and running `scripts/test-it`

**Comment by Ferrumofomega** [comment]
Great, this looks good to me. Thanks Camen!

**Pull request merged**
